filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~


filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ../logs/example.log


# filebeat.logstash:
#  hosts: ["localhost:5044"]


#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'


output.logstash:
  hosts: ["localhost:5044"]



