# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.6/metricbeat-module-elasticsearch.html

- module: elasticsearch
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  hosts: ["http://elasticsearch:9200"]
  metricsets: ["node", "node_stats" ]
  username: "xlouzao"
  password: "xLv.0000"  
  #username: "user"
  #password: "secret"
